url: https://spazioindacocfe.com
#url: http://127.0.0.1:4000
baseurl: 

# Site settings
title: Spazio Indaco
email: info@spazioindacocfe.com
description: "Centro multidisciplinare dedicato alla salute in ogni fase della vita"


# Team names, titles and social links
people:
- name: Anna Maria Riccardo
  pic: Anna
  position: <i>Tecnica della riabilitazione psichiatrica<br>Assistente Analista del Comportamento <br>Co-founder Spazio Indaco <i>
  description: <br> Laureata con Lode in Tecnica della Riabilitazione Psichiatrica all'Università di Modena e Reggio Emilia nel 2021, ho successivamente completato un corso di perfezionamento in <b>"La comunicazione aumentativa alternativa in età evolutiva"</b> presso la stessa università. Nello stesso anno, ho frequentato il corso per <b>tecnico ABA</b> e <b>Tutor DSA e BES</b>. <br> Sono anche un'<b>Assistente Analista del Comportamento</b> in seguito al master di I livello in <b>ABA</b> (Applied Behavior Analysis). <br> Dal 2021, svolgo interventi psicoeducativi rivolti a bambini con <b>autismo</b>,  sia collaborando con la pubblica amministrazione sia come libera professionista.
  social:
    - title: instagram
      url: https://www.instagram.com/anna.riccardo_terp/
    - title: linkedin
      url: https://www.linkedin.com/in/anna-maria-riccardo-62129a224/

- name: Valeria Villani
  pic: ValeriaV
  position: <i>Ostetrica <br> Co-founder Spazio Indaco </i> 
  description: "<br> <br> L'ostetrica è una figura sanitaria essenziale che accompagna le donne in tutte le fasi della loro vita: dall'adolescenza all'età fertile, attraverso la gravidanza il parto e il puerperio, fino alla menopausa. Dopo la mia laurea presso l'Università degli Studi di Roma Tor Vergata nel 2013, ho iniziato la mia carriera lavorativa in un consultorio familiare a Roma. Nel 2015 mi sono trasferita in Emilia Romagna, dove ho dato alla luce i miei due bambini. Successivamente, nel 2019, ho lavorato come ostetrica di reparto e sala parto presso l'Arcispedale Santa Maria Nuova di Reggio Emilia. Nel 2021, ho deciso di intraprendere la strada della libera professione con un obiettivo chiaro: specializzarmi nella <b>salute del pavimento pelvico femminile</b>. Questa scelta è nata dalla mia profonda volontà di aiutare le donne a trovare una figura specializzata che le supporti nei loro percorsi di riabilitazione e benessere pelvico. Ho quindi avviato uno studio dedicato alla rieducazione e riabilitazione pelviperineale, dove posso individuare e trattare le varie problematiche legate al pavimento pelvico, collaborando, quando necessario, con altri professionisti del settore. Oltre la riabilitazione pelvica, offre percorsi di <b>accompagnamento alla nascita</b> per donne e coppia in attesa, <b>assistenza domiciliare durante il puerperio</b>, <b>sostegno all'allattamento al seno</b>, incontri tematici periodici. La mia missione è fornire un'assistenza personalizzata e continua, rispondendo a ogni esigenza delle donne migliorando la loro qualità di vita attraverso una cura attenta e specializzata."
  social:
    - title: instagram
      url: https://www.instagram.com/ostetrica_valeriavillani/
    - title: linkedin
      url: https://www.linkedin.com/in/valeria-villani-8957118a/

- name: Federica Coppola
  pic: Federica
  position: <i>Biologa Nutrizionista</i>
  description: <br> Sono Federica, Biologa <b>Nutrizionista</b>, laureata in Biologia della Salute all'università di Bologna.
    <br>Per me, la <b>nutrizione</b> non è solo una questione di calorie, ma di <b>equilibrio</b>, <b>ascolto</b> e <b>benessere</b> a 360°.
    <br>Come Nutrizionista mi occupo di:<br><b>• Educazione alimentare</b>
    <br>• Piani alimentari per la <b>perdita di peso</b>
    <br>• Piani personalizzati per donne in <b>gravidanza</b>, <b>allattamento</b>, <b>menopausa</b>
    <br>• <b>Nutrizione sportiva</b>, aumento di massa muscolare
    <br>• <b>Mindful eating</b>
    <br><br><b>Cosa posso fare?</b>
    <br>Ti aiuto a trovare un'alimentazione che si adatti alla tua vita, senza rinunce!
    <br>Ti accompagno in un percorso sostenibile, senza stress e senza sensi di colpa.
    <br><br>Credo nella semplicità e nella naturalezza:niente soluzioni rigide, solo scelte consapevoli.
    <br>La tua alimentazione può diventare un'alleata per sentirti meglio e avere più energia ogni giorno.
  social:
    - title: instagram
      url: https://www.instagram.com/nutrizionistafedericacoppola/

- name: Maddalena Barani  
  pic: Maddalena
  position: <i>Logopedista - Età evolutiva</i>
  description: Mi sono laureata in <b>Logopedia</b> presso l'università di Modena e Reggio Emilia a novembre 2022, specializzandomi nella <b>valutazione</b> e nel <b>trattamento</b> del <b>linguaggio</b> e dell'<b>apprendimento</b>.
    <br>Ho arricchito la mia formazione con corsi specifici, ottenendo le qualifiche di:<br><b<Tecnico ABA</b>, con competenze su analisi del comportamento, insegnamento strutturato e gestione dei comportamenti problema nell'autismo.
    <br><b>Tutor DSA, BES e ADHD</b>, per supportare bambini e ragazzi con difficoltà scolastiche attraverso strategie personalizzate.
    <br><br>Attualmente lavoro come logopedista in libera professione occupandomi in particolare modo di:<b>disturbi del linguaggio</b>, DSA e <b>difficoltà di apprendimento</b>, <b>autismo</b> e <b>ritardo cognitivo</b>.
    <br>Oltre alla libera professione collaboro anche con la <b>Neuropsichiatrica Infantile</b> di Modena.
    <br>Nella terapia reputo fondamentale la creazione di una <b>relazione</b> con il <b>paziente</b> e la <b>collaborazione</b> tra le varie parti che compongono il suo ambiente:<b>genitori</b>, <b>rete scolastica</b> e/o altri <b>professionisti</b> che lo seguono.
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/maddalena-barani-17438035b/?originalSubdomain=it

- name: Valeria Santacatterina
  pic: ValeriaS
  position: <i>Logopedista - Età evolutiva</i>
  description: TESTO DA AGGIORNARE
  social:
    - title: instagram
      url: https://www.instagram.com/valelogo_adhd/
    - title: linkedin
      url: https://www.linkedin.com/in/valeria-santacatterina-4130031b7/

- name: Annalisa Montecchi
  pic: Annalisa
  position: <i>Logopedista - Età evolutiva</i>
  description: <br>Mi sono laureata con lode in <b>Logopedia</b> nel 2023 presso l'Università di Modena e Reggio Emilia, e sono iscritta all'Albo dei Logopedisti di Modena e Reggio Emilia (n. 313).
    <br>Dopo la laurea ho svolto un periodo di affiancamento presso lo studio Colibrì.Lab di Maranello, e attualmente lavoro in libera professione a Castelfranco Emilia presso <b>Spazio Indaco</b> e a Modena presso lo studio <b>PersonaLmente</b>.
    <br>Da diversi anni opero anche come <b>educatrice</b> nel progetto <b>Ness1escluso</b>, dedicato ad attività sportive, ricreative e formative per bambini, ragazzi e adulti con disabilità cognitive e comportamentali, e nel contesto scolastico come supporto educativo per bambini con disabilità cognitive o <b>disturbo dello spettro autistico</b>.
    <br>Ho sempre lavorato in contesti multidisciplinari, collaborando con <b>TeRP</b>, psicologi, neuropsicologi, psicomotricisti, educatori e terapisti occupazionali, per garantire una presa in carico globale e favorire il miglior benessere del paziente.
    <br>In un'ottica di <b>formazione continua</b>, ho svolto corsi e workshop prevalentemente dedicati ai <b>disturbi della comunicazione e del linguaggio in età evolutiva</b>, tra cui:<b>Speech Sound Disorders</b> e workshop di introduzione alla tecnica <b>PROMPT</b>.
    <br><br><b>Ambiti di intervento</b>:<br>• Valutazione e trattamento di bambini (0-3 anni) in ritardo nello sviluppo del linguaggio
    <br>• Disturbi specifici di linguaggio e dello speech
    <br>• Disturbi specifici dell'apprendimento (DSA)
    <br>• Squilibrio muscolare oro-facciale e deglutizione (terapia mio-funzionale)
    <br>• Competenze comunicative e linguistiche nei bambini con diagnosi di disturbo dello spettro autistico
    <br>• Consulenza su sviluppo del linguaggio e DSA per famiglie, insegnanti ed educatori
    <br><br>Per la mia pratica clinica mi baso sull'<b>EBM</b> (Evidence Based Medicine):ogni trattamento è guidato da valutazioni standardizzate e dalla letteratura scientifica più aggiornata.
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/annalisa-montecchi-6146411a5/

- name: Giulia Vinciguerra
  pic: Giulia
  position: <i>Logopedista - Età adulto-geriatrica</i>
  description: <br> Mi sono laureata con Lode in <b>Logopedia</b> presso l'Università di Modena e Reggio Emilia a novembre 2022.
    <br>Fin da subito ho scelto di specializzarmi nella <b>valutazione</b> e <b>trattamento</b> delle <b>comunicopatie</b> e dei <b>disturbi di deglutizione in età adulto-geriatrica</b>.
    <br>Ho arricchito perciò il mio percorso con:<br>Tirocinio volontario di un anno presso USL di Reggio Emilia;<br><b>Master di I Livello “Logopedia in area Neurologica”</b>, presso l'Università di Torino, di cui conseguirò il titolo a inizio Giugno 2025.
    <br><br>Attualmente lavoro come libera professionista in collaborazione con:<br><b>Associazione Parkinson Modena - ODV</b><br><b>Associazione A.L.I.Ce Modena - ODV</b><br><b>Ospedale privato-accreditato Villa Pineta di Gaiato</b>, Pavullo.
    <br><br>L'obiettivo di qualsiasi mio intervento è quello di restituire <i>partecipazione, ruolo e dignità</i> alla persona con lo scopo di migliorare la sua qualità di vita e di coloro che la circondano.
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/giulia-vinciguerra-802888264/


# - name: Federica Pipolo
#   pic: 6
#   position: <i>Psicologa e Analista del comportamento Certificata BCBA®</i>
#   description: <br> Mi sono laureata con lode in <b>Psicologia dell'intervento clinico e sociale</b> presso l'università di Parma. <br> Ho poi conseguito il <b>Master di II Livello in ABA (Applied Behavior Analysis)</b> certificandomi prima come <b>Analista del comportamento</b> e poi conseguendo il titolo americano <b>BCBA presso il BACB</b>. <br> Come Psicologa mi occupo di strutturare percorsi di <b>alfabetizzazione emotiva per bambini e adolescenti a sviluppo normotipico o con disturbi del neuro sviluppo</b>. <br> Come <b>Supervisore BCBA</b> sono responsabile clinica e referente di <b>piani di intervento ABA individualizzati</b>. Strutturo e supervisiono interventi riabilitativi per bambini con Disturbo dello Spettro Autistico o disabilità evolutive.
#   social:
#     - title: facebook
#       url: https://www.facebook.com/profile.php?id=100089904520267
#     - title: linkedin
#       url: https://www.linkedin.com/in/federica-pipolo-57bb18194/
      
- name: Stefania Giannino
  pic: StefaniaG
  position: "<i>Psicologa</i>"
  description: |
    <br> <b>Le mie esperienze</b>: 
    <br> • Tirocinante educatrice nella comunità "Coccinella" del gruppo CEIS dove ho potuto interfacciarmi con problematiche di ragazze minori, partecipando alla loro quotidianità e agli incontri di équipe.  
    <br> • Il tirocinio post-laurea magistrale invece l'ho svolto presso lo studio di <b>psicoterapia sistemico-relazionale</b> di Lercara e Cagnone. Il lavoro è stato soprattutto rivolto ai colloqui e qui ho imparato la cura attraverso la relazione terapeutica, nel suo modo di stare e nella sua praticità.  
    <br> • <b>Progetto di affido</b> presso il Comune di Torino che mi ha dato in incarico un utente con problematiche psico-motorie.  
    <br> • Lavoro nelle <b>scuole d’infanzia</b> portando progetti a tema ambientale con l’obiettivo di sensibilizzare.  
    <br>
    <br> <b>Di cosa mi occupo e cosa offro</b>:  
    <br> Offro un servizio di <b>sostegno psicologico</b> per esplorare le tue difficoltà e capire nuovi modi di affrontarle, tenendo in considerazione la tua soggettività. In particolare, puoi rivolgerti a me per:  
    <br> • Difficoltà emotive e relazionali  
    <br> • Difficoltà in periodi di forte cambiamento  
    <br> • Promozione del benessere e gestione di risorse  
    <br> • Interventi di psicoeducazione  
    <br> • Percorsi di sostegno genitoriale  
  social:
     - title: instagram
       url: https://www.instagram.com/spazioterapia_/
     - title: linkedin
       url: "https://www.linkedin.com/in/stefania-giannino-0a655b135/?originalSubdomain=it"

- name: Pier Matteo Fabbri
  pic: Pier
  position: <i>Psicologo, specializzato in Educazione Sessuale</i>
  description: Mi sono laureato con lode in Clinical Psychosexology presso l’Università Sapienza di Roma e mi sono specializzato in Educazione Sessuale presso il Centro Italiano di Sessuologia.Mi interesso di temi legati alla sessualità e al genere. Lavoro con persone adolescenti in una comunità terapeutico-riabilitativa. Nella libera professione mi occupo di psicoeducazione, educazione all’affettività e alla sessualità, e a percorsi di supporto psicologico.
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/pier-matteo-fabbri-394a97254/?originalSubdomain=it

- name: Stefania Baglieri
  pic: StefaniaB
  position: <i>Educatrice Sociale<br>Esperta in Pedagogia Sociale<br>Mediatrice Feuerstein e Bright Start</i>
  description: Mi sono laureata in <b>Educatore Sociale</b> presso l'Università di Bologna (Facoltà di Scienze della Formazione) e ho approfondito negli anni la mia formazione diventando <b>Mediatrice Feuerstein</b> (pas basic e pas standard) presso il Centro per l'Apprendimento Mediato (CAM) di Rimini.
    <br><br>A gennaio 2025 ho concluso con lode il <b>Master di 1° livello</b> in <b>Pedagogia Familiare</b> presso l’INPEF (Istituto Nazionale di Pedagogia Familiare), dove attualmente frequento il <b>2° livello</b> e il <b>corso professionale</b> in <b>Assistente materno e genitoriale</b>.
    <br><br>Ho maturato oltre 10 anni di esperienza nell'ambito psichiatrico lavorando in strutture accreditate in collaborazione con i CSM di Bologna. Ho operato anche come <b>personale educativo scolastico</b> e <b>consulente educativo</b>.
    <br><br>Oggi a Spazio Indaco mi occupo di:<br><b>• Corsi pre e post parto</b> con <b>focus educativo</b>
    <br><b>• Supporto educativo alla maternità e alla genitorialità</b>
    <br><b>• Promozione dello sviluppo del bambino attraverso un approccio metacognitivo</b>
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/stefania-baglieri-6a51441b1/
    - title: instagram
      url: https://www.instagram.com/conoscere_per_crescere/

- name: Linda Borsari
  pic: Linda
  position: <i>Educatrice Pedagogica<br>Psicomotricista<br>Insegnante di Massaggio Infantile AIMI</i>
  description: <br>Mi sono laureata in Scienze dell'Educazione nel 2018 presso l'Università di Ferrara e ho conseguito nel 2023 il diploma triennale di Psicomotricista con tesi su <i>“Memorie prenatali in sala di psicomotricità”</i>. Sono socia ANUPI Educazione e ho maturato 10 anni di esperienza in nidi, scuole dell'infanzia e primarie. Attualmente sto frequentando il Master Universitario di I° livello in <b>Prevenzione, Educazione e Rieducazione del Gesto Grafico</b>, con focus sui Disturbi Specifici dell'Apprendimento.
    <br>Nel 2024 ho ottenuto il 2° livello di Lingua dei Segni e sono diventata mamma di Edoardo.
    <br><br>Mi occupo di:<br>
    🖐️<b>Percorsi psicomotori</b> in un ambiente sicuro e stimolante dove i bambini esplorano corpo, spazio, emozioni e relazioni;
    <br>🖐️<b>Incontri di Massaggio Infantile AIMI</b> per bimbi 0-12 mesi e genitori, momenti di coccole, conoscenza e confronto tra neo genitori;
    <br>🖐️<b>Laboratori creativi propedeutici alla scrittura</b> per bambini dell'ultimo anno della scuola dell'infanzia, per sviluppare prerequisiti attraverso un approccio psico-corporeo.
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/linda-borsari-2ba572145/?original_referer=https%3A%2F%2Fwww%2Egoogle%2Ecom%2F&originalSubdomain=it
    - title: instagram
      url: https://www.instagram.com/psicomotri_linda/

- name: Alessandra Paradiso
  pic: Alessandra
  position: <i>Insegnante di YOGA</i><br>Viniyoga
  description: <br>Trasmetto lo <b>yoga</b> come disciplina olistica che unisce <b>corpo, mente e anima</b>, basandomi sulla mia esperienza personale e professionale.
    <br>La mia formazione deriva dalla scuola <b>VINIYOGA</b>, che si fonda sugli insegnamenti del maestro <b>Tirumalai Krishnamacharya</b>. In questo approccio, lo yoga si modella sul singolo individuo come un <i>“abito su misura”</i>, adattandosi alle sue caratteristiche fisiche, mentali ed emotive.
    <br>Credo che, con una pratica costante, la profonda connessione tra <b>respiro e movimento</b> possa offrire uno strumento per rallentare, ritrovare equilibrio e coltivare una relazione più autentica con sé stessi e con il mondo che ci circonda.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/spazio.indaco/?igsh=YmJ2b3ZhZzV4am82&utm_source=qr
  - title: linkedin
    url: https://www.linkedin.com/company/spazio-indaco-cfe/
  
# Postal address (add as many lines as necessary)
address: |
  Via del Maniscalco, 30<br>
  Castelfranco Emilia (Modena)

# Build settings
markdown: kramdown
permalink: pretty