url: https://spazioindacocfe.com
#url: http://127.0.0.1:4000
baseurl: 

# Site settings
title: Spazio Indaco
email: info@spazioindacocfe.com
description: "descrizione che vuoi che esca su google"


# Team names, titles and social links
people:
- name: Anna Maria Riccardo
  pic: 1
  position: Tecnico della riabilitazione psichiatrica
  social:
    - title: instagram
      url: #
    - title: linkedin
      url: #

- name: Valeria Villani
  pic: 2
  position: Ostetrica
  social:
    - title: instagram
      url: #
    - title: linkedin
      url: #

- name: Elisa Zacheo
  pic: 3
  position: Logopedista
  social:
    - title: linkedin
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty