#url: https://spazioindacocfe.com
url: http://127.0.0.1:4000
baseurl: 

# Site settings
title: Spazio Indaco
email: info@spazioindacocfe.com
description: "Centro multidisciplinare dedicato alla salute in ogni fase della vita"


# Team names, titles and social links
people:
- name: Anna Maria Riccardo
  pic: 1
  position: Tecnico della riabilitazione psichiatrica
  social:
    - title: instagram
      url: https://www.instagram.com/anna.riccardo_terp/
    - title: linkedin
      url: https://www.linkedin.com/in/anna-maria-riccardo-62129a224/

- name: Valeria Villani
  pic: 2
  position: Ostetrica
  social:
    - title: instagram
      url: https://www.instagram.com/ostetrica_valeriavillani/
    - title: linkedin
      url: https://www.linkedin.com/in/valeria-villani-8957118a/

- name: Elisa Zacheo
  pic: 3
  position: Logopedista
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/elisa-zacheo-44786b228/


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/spazio.indaco/?igsh=YmJ2b3ZhZzV4am82&utm_source=qr
  
# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty